version: '3.8'

services:
  mysql:
    image: mysql:5.6
    container_name: mysql
    environment:
      MYSQL_DATABASE: moviewise
      MYSQL_USER: my_root
      MYSQL_PASSWORD: qwerty1234
      MYSQL_ROOT_PASSWORD: Qwerty1234
    volumes:
      - ./resources:/docker-entrypoint-initdb.d
      - fpg_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - pfg-moviewise

  php:
    build: .
    container_name: php
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/php.ini:/usr/local/etc/php/php.ini
    depends_on: 
      - mysql
    links:
      - mysql
    networks:
      - pfg-moviewise


volumes:
  fpg_data: {}

networks:
  pfg-moviewise:
    driver: bridge